<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaXaml Remove="Assets\Icons.axaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.7" />
    <PackageReference Include="Avalonia.Markup.Xaml.Loader" Version="11.2.7" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.7" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.7" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.2.7" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.Avalonia" Version="2.0.0-rc5.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Update="Assets\Icons.axaml">
      <SubType>Designer</SubType>
    </AvaloniaResource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\ScaleOverviewPageView.axaml.cs">
      <DependentUpon>ScaleOverviewPageView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\HomePageView.axaml.cs">
      <DependentUpon>HomePageView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\SidebarMenuView.axaml.cs">
      <DependentUpon>SidebarMenuView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\Images\" />
  </ItemGroup>
</Project>
